### ISSUE TITLE
Hi!~ Is it for reCaptcha v2？

### ISSUE THREAD

**Issue by Xwudao** [DongKyuuuu/vue3-recaptcha-v2#1]
It has two versions of reCatpcha, v2 and v3.

This library is for v2?

**Comment by Dongkyuuuu** [comment]
@Xwudao yes, this library is `reCAPTCHA v2`

**Comment by Xwudao** [comment]
> @Xwudao yes, this library is `reCAPTCHA v2`

thanks for reply.
