### ISSUE TITLE
How to set sitekey dynamically?

### ISSUE THREAD

**Issue by tfevan** [DongKyuuuu/vue3-recaptcha-v2#14]
The `sitekey` in my project isn't static; I grab it from the API.
Is it possible to set the `sitekey `dynamically?

**Comment by Dongkyuuuu** [comment]
@tfevan 
In the version before v2.0.2, dynamic siteKey could not be used. However, with the v2.1.0 update, it is now supported. You can check the [documentation](https://github.com/Dongkyuuuu/vue3-recaptcha-v2/tree/v2.1.0?tab=readme-ov-file#dynamic-sitekey) for more details.

**Comment by tfevan** [comment]
@Dongkyuuuu 
I appreciate the new version, **thank you**.
