### ISSUE TITLE
Does the render of several captchas work correctly?

### ISSUE THREAD

**Issue by AlekseiKromski** [DongKyuuuu/vue3-recaptcha-v2#17]
Hi, I am currently working on a project and started using this package.

In `main.js` I set the following code:

```js
.use(install, {
    sitekey: "XXX",
    cnDomains: false,
})
```

But when I tried to use the `RecaptchaV2` component twice on the same Vue component, I encountered that only the last one was rendered

Maybe it's not a problem, but anyway thank y!

**Comment by Dongkyuuuu** [comment]
@AlekseiKromski 
Hi!

I think need to create multiple scripts to call the `RecaptchaV2` component multiple times, but we don't support that feature yet. (create script once after `RecaptchaV2` component render before)

Thanks for the report!

**Comment by AlekseiKromski** [comment]
thank you for the answer, at the moment I was able to solve the problem by using the v-if condition depending on which component is currently active.

I think we can close this thread, thanks again!!
