### ISSUE TITLE
The official domain name cannot be accessed in some places

### ISSUE THREAD

**Issue by Xwudao** [DongKyuuuu/vue3-recaptcha-v2#2]
such as China.

Replace it with `https://recaptcha.net`, maybe is a good idea?

https://github.com/DongKyuuuu/vue3-recaptcha-v2/blob/main/src/config/install.ts#L28

**Comment by Dongkyuuuu** [comment]
It seems a good idea, but I think it's better to provide install option like `alternative Domain`. What do you think about it?

**Comment by Xwudao** [comment]
> It seems a good idea, but I think it's better to provide install option like `alternative Domain`. What do you think about it?

If so, it would be better

**Comment by Dongkyuuuu** [comment]
this feature updated to `v0.3.0`. thanks!
@Xwudao

**Comment by Xwudao** [comment]
> this feature updated to `v0.3.0`. thanks!
> @Xwudao

good!

Thanks
