### ISSUE TITLE
vue3-recaptcha-v2 doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module

### ISSUE THREAD

**Issue by imShara** [DongKyuuuu/vue3-recaptcha-v2#4]
Hi. I'm using it with Vite and got this error in dev mode:

> vue3-recaptcha-v2 doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

**Comment by Dongkyuuuu** [comment]
thx!
This PR is updated. you can use v1.0.1

solve #5
